name: test-orders

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Orders Module Test Suite
        run: cd orders && npm install && npm run test:ci
